---
baseURL: https://alexnuttinck.dev/
languageCode: en-us
title: "Alexandre Nuttinck"
theme: "toha"
canonifyurls: true
enableRobotsTXT: true
disqusShortname: does-not-exist
enableEmoji: true

languages:
  en:
    languageName: English
    weight: 1
  # fr:
  #   languageName: Français
  #   weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Custom parameters
params:
  gitRepo: https://github.com/alexnuttinck/alexnuttinck.github.io
  copyright: Alexandre Nuttinck © 2020
  description: Creating open source software.
  background: images/background.jpg
  logo:
    favicon: /images/favicon.png

  author:
    name: "Alexandre Nuttinck"
    nickname: "Alex"
    image: "images/avatar.png"
    greeting: "Hi, I am"
    contactInfo:
      email: "contact@alexnuttinck.dev"
    summary:
      - "I'm a Research Engineer"
      - "I'm interested in Distributed Systems and Kubernetes"
      - "I love to work on opensource projects"

  enableBlogPost: false
  enableTOC: true

#  customMenus:
#  - name: Notes
#    url: https://hossainnotes.netlify.app/docs/example/

  newsletter:
    enable: false
